### PR TITLE
fix documentation

### PR DESCRIPTION
**Pull request by takinbo**
Installation instructions currently point the user at the github repository. This PR fixes that by pointing the installation at npm.

### CODE REVIEW

**Comment by NicolasDorier** [comment]
Sexy! I think the package is not published yet though?

**Comment by takinbo** [comment]
It is currently published at https://www.npmjs.com/package/btcpay

**Comment by NicolasDorier** [comment]
@takinbo the link you give me say `npm install btcpayserver/node-btcpay`

**Comment by takinbo** [comment]
Yup. That's what this PR fixes.

**Comment by NicolasDorier** [comment]
no, this PR changed to `npm install btcpay`

**Comment by NicolasDorier** [comment]
It seems both works? I don't understand why.

**Comment by takinbo** [comment]
Correct. Installing using ```btcpayserver/node-btcpay``` will install from GitHub rather than npm. This PR changed those instructions so the installation is made from npm.

**Comment by takinbo** [comment]
0.2.1 has been published to npm. The updated instructions are now in effect.

**Comment by NicolasDorier** [comment]
oooh got it thanks a lot!

**Comment by NicolasDorier** [comment]
when you have time, can you add me as owner of the repo as well ? `nicolas.dorier`

**Comment by NicolasDorier** [comment]
oh you did

**Comment by takinbo** [comment]
yes I did :)

**Comment by NicolasDorier** [comment]
At the orga level would be nice as well so I can create more repo later. (When we get a new API for other stuff than invoicing)

**Comment by takinbo** [comment]
I also created an org and invited you to it.

**Comment by NicolasDorier** [comment]
Awesome very excited! It makes it so easy for people to get started!

**Comment by takinbo** [comment]
in deed!

**Pull request merged**
