### PR TITLE
Fix Invoice.exceptionStatus type

### PR DESCRIPTION
**Pull request by AryanJ-NYC**

### CODE REVIEW

**Comment by wallopthecat** [comment]
LGTM ty

**Comment by junderw** [comment]
Missing `'marked'`

https://github.com/btcpayserver/btcpayserver/blob/e2e37a0db4e00880eacdcd03c4d1413568385cae/BTCPayServer/Services/Invoices/InvoiceEntity.cs#L633-L637

**Review by junderw — CHANGES_REQUESTED** [review]
Add `'marked'` please.

**Comment by takinbo** [comment]
Is the `false` status also not a string? [This](https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/Services/Invoices/InvoiceEntity.cs#L639) seems to suggest so?

**Comment by junderw** [comment]
It looks like the status to string dictionary is created before the "false" is added... so it should output `string.Empty` for `toString`

........ however I don't know how The JSON serializer will treat that... `''`?

**Comment by junderw** [comment]
In general, this exception will never be set by the client, so we need to figure out how the server will convert the status to JSON and send it to the client...

@NicolasDorier Any clues?

**Comment by junderw** [comment]
Looks like the server responds with boolean false (I added a console.log to the test suite to see the invoice data)

スクリーンショット_2021-02-07_11-29-32

**Comment by junderw** [comment]
Looks like the Client app has an extra `Invalid` status as well...

https://github.com/btcpayserver/btcpayserver/blob/9e71c02eb9a67ec5dc35289409a28fd7abeda926/BTCPayServer.Client/Models/InvoiceExceptionStatus.cs

**Comment by junderw** [comment]
On the server side this doesn't exist though... :-/

meh, imo this PR + "marked" is probably the right solution.

**Comment by AryanJ-NYC** [comment]
'marked' added

**Review by junderw — APPROVED** [review]
LGTM

**Comment by takinbo** [comment]
LGTM!

Thanks for the PR @AryanJ-NYC and for the review @junderw.

**Review by takinbo — APPROVED** [review]

**Pull request merged**
