### PR TITLE
add distribution files

### PR DESCRIPTION
**Pull request by takinbo**
Noticed that the PR by @Uter1007 did not include the distribution files which would enable the project to be installed and used without transpiling first and so I went ahead to get that done with this PR.

### CODE REVIEW

**Comment by NicolasDorier** [comment]
I don't know what the best practice for TS projects.
So basically this is done some somebody can just copy paste the `client.js` and play with it without NPM?

**Comment by takinbo** [comment]
I suspect that one could actually do that without installing the project with NPM but for those who install the package using NPM (as the documentation suggests), this PR includes the transpiled ```client.js``` so that they don't need to transpile it themselves.

**Comment by NicolasDorier** [comment]
@takinbo I don't understand the problem. When you upload a package on NPM, you transpile first and upload this along with the type definition right?
How do you upload the package on NPM?

**Comment by NicolasDorier** [comment]
ping @junderw since you maintain bitcoin.js any idea what is the best practice here?

**Comment by junderw** [comment]
#15 should fix this problem.

I added the build step as a postinstall script, so anyone that clones from git will just need to run `npm install` and the built files should be there.

**Comment by NicolasDorier** [comment]
I propose to close this PR in favor of #15 @takinbo

**Pull request closed without merging**
