### PR TITLE
#1 Typescript

### PR DESCRIPTION
**Pull request by Uter1007**
With running npm run build a dist folder should be created. I've added two sample files for a javascript / typescript projects. Please try it out and give me Feedback is that the right direction. 

Cheers,
Christoph ;)

### CODE REVIEW

**Comment by takinbo** [comment]
Thanks @Uter1007. As I understand it, the ```master``` branch is more recent than the ```dev``` branch. Any reason you submitted the PR against the ```dev``` branch?

**Comment by takinbo** [comment]
@NicolasDorier could you also review?

**Comment by Uter1007** [comment]
oops sorry thought dev would be further (haven't looked in detail on it). I can create a new pull request if you like. Alternative: https://github.com/lean-coders/node-btcpay. Cheers

**Comment by Uter1007** [comment]
Have a small fix -> tryped request without request-promise. I will create new pull request with master

**Pull request closed without merging**
